PREP(compile)
PREP(getStaticCameraOffset)
PREP(init)
PREP(initSettings)
PREP(setMonitor)
PREP(setOperator)
PREP(setStaticCamera)

// -- Category actions --
FOLDER_PATH(actions)
PREP(checkNewOpsActionCondition)
PREP(connectActionCondition)
PREP(connectDroneActionCondition)
PREP(disconnectActionCondition)
PREP(enterFullScreenActionCondition)
PREP(exitFullScreenActionCondition)
PREP(fixFeedActionCondition)
PREP(handMonitorMenuActionCondition)
PREP(isWatchingAtMonitor)
PREP(menuActionCondition)
PREP(menuCloseActionCondition)
PREP(operatorInfoActionCondition)
PREP(operatorZoomActionsCondition)
PREP(stopWatchTabletActionCondition)
PREP(switchCameraToGunnerActionCondition)
PREP(switchCameraToPilotActionCondition)
PREP(switchCameraTurretActionCondition)
PREP(switchUAVActionCondition)
PREP(toggleNvgActionCondition)
PREP(toggleTiActionCondition)
PREP(turnOffActionCondition)
PREP(turnOnActionCondition)
PREP(watchTabletActionCondition)
PREP(zoomActionsCondition)
PREP(zoomInActionCondition)

// -- Category camera --
FOLDER_PATH(camera)
PREP(cameraType)
PREP(camPosGoPro)
PREP(camPosPilotTurret)
PREP(camPosStatic)
PREP(camPosVehStatic)
PREP(camPosVehTurret)
PREP(createCamera)
PREP(destroyCamera)
PREP(getCameraPoints)

// -- Category cameraMove --
FOLDER_PATH(cameraMove)
PREP(calculateCameraMoves)
PREP(calculateCurrentCameraMoves)
PREP(cameraMove)
PREP(cameraTurnDownKeybind)
PREP(cameraTurnLeftKeybind)
PREP(cameraTurnRightKeybind)
PREP(cameraTurnUpKeybind)
PREP(defineCameraMovementOptions)
PREP(monitorCameraMove)
PREP(monitorCameraTurnDown)
PREP(monitorCameraTurnLeft)
PREP(monitorCameraTurnRight)
PREP(monitorCameraTurnUp)
PREP(rotateAroundAxis)
PREP(transformTurret)

// -- Category Classes --
FOLDER_PATH(Classes)
PREP(compileClasses)

// -- Category common --
FOLDER_PATH(common)
PREP(compareVectors)
PREP(copyMenuActionsToObj)
PREP(getFovForZoom)
PREP(getMemPointOffsetInModelSpace)
PREP(getNextRenderTarget)
PREP(getObjCamOffsetMS)
PREP(getPlayer)
PREP(getPositionByVectors)
PREP(getTurretCameraLock)
PREP(getVectorUpFromDir)
PREP(hasUAVterminal)
PREP(isPilotControlled)
PREP(isUAV)
PREP(isUAVControlled)
PREP(onTempDisplayUnload)
PREP(randInt)
PREP(remoteExec)
PREP(smoothRotateCam)
PREP(syncState)
PREP(takeUAVcontorls)
PREP(translateLocalVectors)
PREP(hackDrone)

// -- Category keybinds --
FOLDER_PATH(keybinds)
PREP(exitFullscreenKeybind)
PREP(monitorSwitchNVGKeybind)
PREP(monitorSwitchTIKeybind)
PREP(nextTurretKeybind)
PREP(takeUavCtrlKeybind)
PREP(zoomInKeybind)
PREP(zoomOperatorKeybind)
PREP(zoomOutKeybind)
PREP(zoomResetKeybind)

// -- Category monitor --
FOLDER_PATH(monitor)
PREP(closePIPwindow)
PREP(connectMonitorToOperator)
PREP(createPIPwindow)
PREP(disconnectMonitorFromOperator)
PREP(disconnectMonitorFromOperatorKeybind)
PREP(enterMonitorFullScreen)
PREP(exitFullScreen)
PREP(exitMonitorFullScreen)
PREP(fixFeed)
PREP(fixFeedKeybind)
PREP(getTargetMonitor)
PREP(handMonitorCondition)
PREP(monitorCloseMenu)
PREP(monitorFeedActive)
PREP(monitorNextTurretCamera)
PREP(monitorSwitchTi)
PREP(monitorToggleNVG)
PREP(monitorWeakConnection)
PREP(resetFeed)
PREP(setHandDisplay)
PREP(setMonitorPiPEffect)
PREP(setR2TTexture)
PREP(switchUAV)
PREP(turnOffMonitorLocal)
PREP(turnOnMonitorLocal)
PREP(turnOnOffMonitorLocalKeybind)
PREP(zoom)

// -- Category operator --
FOLDER_PATH(operator)
PREP(addActiveTurret)
PREP(checkForNewOperators)
PREP(checkIfNewOperator)
PREP(checkIfOperatorFeedsToAnyMonitor)
PREP(checkOperatorTurrets)
PREP(checkupAllActiveOperators)
PREP(doCheckTurretLocality)
PREP(getActiveOperators)
PREP(getActiveOperatorsCheckGlobal)
PREP(getOperatorClass)
PREP(getOperatorInfo)
PREP(getOperatorName)
PREP(getTurretIndex)
PREP(goProCondition)
PREP(operatorCondition)
PREP(operatorMonitorConnectedEvent)
PREP(operatorMonitorDisconnectedEvent)
PREP(operatorsLocalityChangedEvent)
PREP(removeActiveTurret)
PREP(setOperatorInfo)
PREP(setOperatorSides)
PREP(setTurretParams)
PREP(setupNvgAndTI)
PREP(startOperatorFeed)
PREP(stopOperatorFeed)
PREP(syncOperators)
PREP(turretChangedLocalOperator)
PREP(validClassType)

// -- Category operator\pointParams --
FOLDER_PATH(operator\pointParams)
PREP(getPPAddArr)
PREP(getPPDir)
PREP(getPPLod)
PREP(getPPMemPoint)
PREP(getPPPos)
PREP(getPPSetArr)
PREP(getPPTurret)
PREP(getPPUp)
PREP(setPPAddArr)
PREP(setPPDir)
PREP(setPPLod)
PREP(setPPMemPoint)
PREP(setPPPos)
PREP(setPPSetArr)
PREP(setPPTurret)
PREP(setPPUp)
PREP(validatePointParams)
PREP(setDefaultPointAlignment)
PREP(getDefaultPointAlignment)
PREP(initDefaultPointsAlignment)
PREP(setPointAlignment)

// -- Category UITexture --
FOLDER_PATH(UITexture)
PREP(defineInterfaceData)
PREP(defineSignalEffectFunc)
PREP(drone_checkRebEffect)
PREP(drone_effects)
PREP(drone_initInterface)
PREP(drone_updateInterface)
PREP(effectsFunc)
PREP(interfaceFunc)
PREP(radioNoiseEffect)
PREP(signalFunc)

// -- Category UITexture\fpvUI --
FOLDER_PATH(UITexture\fpvUI)
PREP(fpv_effects)
PREP(fpv_getSignal)
PREP(fpv_handleBattery)
PREP(fpv_handleSignal)
PREP(fpv_handleTime)
PREP(initFPVInterface)
PREP(updateFPVInterface)

// -- Category UITexture\mavicUI --
FOLDER_PATH(UITexture\mavicUI)
PREP(initMavicInterface)
PREP(updateMavicInterface)

// -- Category UITexture\zalaUI --
FOLDER_PATH(UITexture\zalaUI)
PREP(initZalaInterfaceDriver)
PREP(initZalaInterfaceGunner)
PREP(zala_drawHudDriver)
PREP(zala_drawHudGunner)

// -- Category updates --
FOLDER_PATH(updates)
PREP(memoryPointAlignment)
PREP(onEachFrameClient)
PREP(serverLoop)
PREP(serverSyncVariables)
PREP(setupDraw3dEH)
PREP(updateActiveOperatorsLocalTurrets)
PREP(setupOpSyncVarEH)
PREP(timeInterpolate)
PREP(updateCamera)
PREP(updateLocalOperators)
PREP(updateMonitor)
PREP(updateMonitorCamera)
PREP(updateOperator)
PREP(updateOperatorZoom)
PREP(updatePlayerOperator)
PREP(updateTurretCamera)
