PREP(compile)
PREP(getStaticCameraOffset)
PREP(init)
PREP(initSettings)
PREP(setMonitor)
PREP(setOperator)
PREP(setStaticCamera)

// -- Category actions --
FOLDER_PATH(actions)
PREP(checkNewOpsActionCondition)
PREP(connectActionCondition)
PREP(connectDroneActionCondition)
PREP(disconnectActionCondition)
PREP(enterFullScreenActionCondition)
PREP(exitFullScreenActionCondition)
PREP(fixFeedActionCondition)
PREP(handMonitorMenuActionCondition)
PREP(isWatchingAtMonitor)
PREP(menuActionCondition)
PREP(menuCloseActionCondition)
PREP(operatorInfoActionCondition)
PREP(operatorZoomActionsCondition)
PREP(stopWatchTabletActionCondition)
PREP(switchCameraToGunnerActionCondition)
PREP(switchCameraToPilotActionCondition)
PREP(switchCameraTurretActionCondition)
PREP(switchUAVActionCondition)
PREP(toggleNvgActionCondition)
PREP(toggleTiActionCondition)
PREP(turnOffActionCondition)
PREP(turnOnActionCondition)
PREP(watchTabletActionCondition)
PREP(zoomActionsCondition)
PREP(zoomInActionCondition)

// -- Category camera --
FOLDER_PATH(camera)
PREP(cameraType)
PREP(camPosGoPro)
PREP(camPosPilotTurret)
PREP(camPosStatic)
PREP(camPosVehStatic)
PREP(camPosVehTurret)
PREP(createCamera)
PREP(destroyCamera)
PREP(getCameraPoints)

// -- Category cameraMove --
FOLDER_PATH(cameraMove)
PREP(cameraMove)
PREP(defineCameraMovementOptions)
PREP(monitorCameraMove)
PREP(monitorCameraTurnDown)
PREP(monitorCameraTurnLeft)
PREP(monitorCameraTurnRight)
PREP(monitorCameraTurnUp)
PREP(rotateAroundAxis)
PREP(transformTurret)

// -- Category Classes --
FOLDER_PATH(Classes)
PREP(classSystemCompile)
PREP(compileClasses)

// -- Category common --
FOLDER_PATH(common)
PREP(compareVectors)
PREP(copyMenuActionsToObj)
PREP(getFovForZoom)
PREP(getMemPointOffsetInModelSpace)
PREP(getNextRenderTarget)
PREP(getPlayer)
PREP(hasUAVterminal)
PREP(isPilotControlled)
PREP(isUAV)
PREP(onTempDisplayUnload)
PREP(remoteExec)
PREP(syncState)
PREP(takeUAVcontorls)

// -- Category monitor --
FOLDER_PATH(monitor)
PREP(closePIPwindow)
PREP(connectMonitorToOperator)
PREP(createPIPwindow)
PREP(disconnectMonitorFromOperator)
PREP(disconnectMonitorFromOperatorKeybind)
PREP(enterMonitorFullScreen)
PREP(exitFullScreen)
PREP(exitMonitorFullScreen)
PREP(fixFeed)
PREP(fixFeedKeybind)
PREP(getTargetMonitor)
PREP(handMonitorCondition)
PREP(monitorCloseMenu)
PREP(monitorFeedActive)
PREP(monitorNextTurretCamera)
PREP(monitorSwitchTi)
PREP(monitorToggleNVG)
PREP(monitorWeakConnection)
PREP(resetFeed)
PREP(setHandDisplay)
PREP(setMonitorPiPEffect)
PREP(setR2TTexture)
PREP(turnOffMonitorLocal)
PREP(turnOnMonitorLocal)
PREP(turnOnOffMonitorLocalKeybind)
PREP(zoom)

// -- Category operator --
FOLDER_PATH(operator)
PREP(addActiveTurret)
PREP(checkForNewOperators)
PREP(checkIfNewOperator)
PREP(checkOperatorTurrets)
PREP(checkupAllActiveOperators)
PREP(doCheckTurretLocality)
PREP(getActiveOperators)
PREP(getActiveOperatorsCheckGlobal)
PREP(getOperatorClass)
PREP(getTurretIndex)
PREP(goProCondition)
PREP(initDefaultPointsAlignment)
PREP(operatorCondition)
PREP(removeActiveTurret)
PREP(setDefaultPointAlignment)
PREP(setPointAlignment)
PREP(setTurretParams)
PREP(setupNvgAndTI)
PREP(startOperatorFeed)
PREP(stopOperatorFeed)
PREP(syncOperators)
PREP(validClassType)

// -- Category updates --
FOLDER_PATH(updates)
PREP(memoryPointAlignment)
PREP(onEachFrameClient)
PREP(serverLoop)
PREP(setupDraw3dEH)
PREP(setupOpSyncVarEH)
PREP(timeInterpolate)
PREP(updateCamera)
PREP(updateLocalOperators)
PREP(updateMonitor)
PREP(updateMonitorCamera)
PREP(updateOperator)
PREP(updateOperatorZoom)
PREP(updatePlayerOperator)
PREP(updateTurretCamera)
